# Generated by Django 5.0 on 2024-03-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0004_payment_orderplaced'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
